# Generated by Django 5.2.7 on 2025-10-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Delivery'), ('cod', 'Cash on Delivery'), ('razorpay', 'Razorpay')], max_length=20),
        ),
    ]
